<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: minhthunguyen
 * Date: Thu, 27 Feb 2025 08:33:45 +0000
 */

$conf['title'] = 'IndigiTech';
$conf['start'] = 'Home';
$conf['template'] = 'arcadebasic';
$conf['license'] = 'cc-by-sa';
$conf['toptoclevel'] = '2';
$conf['tocminheads'] = '0';
$conf['maxtoclevel'] = '0';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'recent,register,media';
$conf['plugin']['addnewpage']['addpage_showroot'] = 0;
$conf['plugin']['addnewpage']['addpage_hide'] = 0;
$conf['plugin']['adhoctags']['allowedElements'] = 'b,aside,i,section,s,figure,u,figcaption,q,article,abbr,header,mark,footer,address,small,cite,em,time,h1,h2,kbd,h3,h4,h5,h6,a,dl,dd,details,summary,div';
$conf['plugin']['gallery']['options'] = 'cache,crop,lightbox';
$conf['plugin']['toctweak']['tocminheads'] = '0';
$conf['tpl']['arcadebasic']['discussionPage'] = '';
$conf['tpl']['arcadebasic']['userPage'] = '';
$conf['tpl']['bootstrap3']['socialShareProviders'] = 'facebook,linkedin,microsoft-teams,pinterest,whatsapp,reddit,twitter,telegram,yammer,google-plus';
