# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Wed, 08 Jan 2025 09:53:54 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

minhthunguyen:$2y$10$5J0dNeeXkPeHGSxREBaIUebJv8PmOFTY2KxArtW/n/5Zjbl0QR.cq:Minh Thu Nguyen:minhthunguyen@swin.edu.au:admin,user
